version: "3"

services:
  gmod:
    build: .
    environment:
      - SRCDS_TOKEN=0
      - GAMETYPE=terrortown
      - RCON_PWD=changeme
    ports:
      - "27015:27015/udp"
    volumes:
      - garrysmod-data:/garrysmod

volumes:
  garrysmod-data:
