version: "3"
   
services:
  gmod:
    build: .
    volumes:
      - ./garrysmod-data/:/home/steam/garrysmod-dedicated/
    network_mode: "host"
    environment: 
      - SRCDS_PORT=27015
      - SRCDS_TOKEN=0
      - GAMETYPE=TTT